name: GHAPI Bug Labeling
on: issue_comment

permissions:
  issues: write
  pull-requests: write

jobs:
  ghapi-bug-labeling:
    # check if the pull request body contains the string "/bug"
    if: (github.event.issue.pull_request != null) && contains(github.event.comment.body, '/bug')
    runs-on: ubuntu-latest
    steps:        
    - name: install dependencies
      run: pip install ghapi 

      # this step is for debugging purposes only, so you can see the payload.
    - name: see payload
      run: echo "PAYLOAD:\n${PAYLOAD}\n"
      env:
        PAYLOAD: ${{ toJSON(github.event) }}
      
    - name: Make a comment
      shell: python
      run: |  # We tipically do this inside a python script
        import os
        from ghapi.core import GhApi
        owner,repo = os.environ['REPO'].split('/')
        api = GhApi(owner=owner, repo=repo)
        api.issues.add_labels(issue_number=os.environ['NUMBER'], labels=['bug'])
      env:
        NUMBER: ${{ github.event.issue.number }} 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPO: ${{ github.repository }}
