name: Experiment linked to PR check
on: 
  pull_request:
    types: [labeled, unlabeled]

jobs:
  check-linked-experiment:
    runs-on: ubuntu-latest
    steps:

      - name: Install ghapi
        run: pip install ghapi

      - name: Check that 'experiment-linked' label exists
        shell: python
        run: |
          import os
          from ghapi.core import GhApi
          owner,repo = os.environ['REPO'].split('/')
          api = GhApi(owner=owner, repo=repo)
          pull = api.pulls.get(os.environ['NUMBER'])
          labels = [l.name for l in pull.labels]
          assert 'experiment-linked' in labels, "The PR does not have the required label 'experiment-linked'"
        env:
          NUMBER: ${{ github.event.number }} 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
 