name: ghapi

# run every time a pull request is opened or updated
on: pull_request

# The permissions section gives our GitHub Action permission
# to extend the things we can do by default. In this case,
# we're asking for permission to read the contents of the
# repository and write to issues and pull requests.
permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  ghapi:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: pip install ghapi

      - name: Make a comment
        shell: python
        run: |  # We tipically do this inside a python script
          import os
          from ghapi.core import GhApi
          owner, repo = os.environ['REPO'].split('/')
          api = GhApi(owner=owner, repo=repo)
          api.issues.create_comment(
            issue_number=os.environ['NUMBER'],
            body='Hello world from a workflow job!'
          )
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.pull_request.number }}
              