name: GitHub Actions Secrets Demo

on: push

jobs:
  secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Reveal
        env:
          MY_PASS: ${{ secrets.MY_SECRET }}
        shell: python
        run: |
          import os
          print(len(os.getenv['MY_PASS']))
    